<!-- ### Article {{i}} -->

<!-- #### Article `r '{{value.pancreas_PMID}}'`. -->

```{r, include=FALSE}
# {{value.pancreas_PMID}}
PMID <- '{{value.pancreas_PMID}}'

pancreas_article <- pancreas[pancreas[["PMID"]] == PMID, ]


```


```{r include=FALSE}
PubMedString <- "PubMed: https://www.ncbi.nlm.nih.gov/pubmed/?term="
doiString <- "doi: https://doi.org/"
```


```{r include=FALSE}

article_citation <- paste0(
  pancreas_article$ArticleTitle,
                   ' ',
  pancreas_article$Title,
                   ' ',
                   pancreas_article$YearArticleDate,
                   ' ',
                   pancreas_article$MonthArticleDate,
                   ';',
                   pancreas_article$Volume,
                   '(',
                   pancreas_article$Issue,
                   ')'
                   )

article_citation <- gsub(pattern = 'NA', replacement = '', x = article_citation)

PubMed_link <- paste0(PubMedString, pancreas_article$PMID)

doi_link <- paste0(doiString, pancreas_article$DOI)

```



<details open> <summary>
- **`r pancreas_article$ArticleTitle`**
</summary>

*`r article_citation`*

`r PubMed_link`

`r pancreas_article$AbstractText`

`r doi_link`

</details>

---


