---
title: "Ampulla"
output: html_document
---

```{r global_options}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      include = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE
                      )
```


```{r read ampulla_PMIDs, include=FALSE}

ampulla_PMIDs <- read.csv(file = "data/ampulla_PMIDs.txt",
                          header = FALSE
)

exclude_ampulla_PMIDs <- read.csv(file = "data/exclude_ampulla_PMIDs.txt",
                                  header = FALSE
)

ampulla_PMIDs$V1 <- unique(ampulla_PMIDs$V1)

ampulla_PMIDs$V1 <- ampulla_PMIDs$V1[! ampulla_PMIDs$V1 %in% exclude_ampulla_PMIDs$V1]


readr::write_csv(x = ampulla_PMIDs,
                 file = "data/ampulla_PMIDs.txt",
                 col_names = FALSE
)

```


```{r include=FALSE}
out_ampulla = NULL
for (i in 1:length(ampulla_PMIDs)) {
  value.ampulla_PMID <- ampulla_PMIDs[i]
  out_ampulla = c(out_ampulla,
          knitr::knit_expand('_ampulla_child.Rmd')
  )
  }

```



`r paste(knitr::knit(text = out_ampulla), collapse = '\n\n\n')`



