journals <- paste0(
    "Acta Cytol[Journal] OR ",
    "Adv Anat Pathol[Journal] OR ",
    "Am J Clin Pathol[Journal] OR ",
    "Am J Gastroenterol[Journal] OR ",
    "Am J Pathol[Journal] OR ",
    "Am J Surg Pathol[Journal] OR ",
    "Anal Cell Pathol [Journal] OR ",
    "Ann Diagn Pathol[Journal] OR ",
    "Ann Pathol[Journal] OR ",
    "Ann Surg Oncol[Journal] OR ",
    "Ann Surg[Journal] OR ",
    "Annu Rev Pathol[Journal] OR ",
    "APMIS[Journal] OR ",
    "Appl Immunohistochem Mol Morphol[Journal] OR ",
    "Arch Pathol Lab Med[Journal] OR ",
    "Cancer Cell[Journal] OR ",
    "Cancer Cytopathol[Journal] OR ",
    "Cancer[Journal] OR ",
    "Cell Oncol[Journal] OR ",
    "Cell[Journal] OR ",
    "Clin Cancer Res[Journal] OR ",
    "Cytojournal[Journal] OR ",
    "Cytopathology[Journal] OR ",
    "Diagn Cytopathol[Journal] OR ",
    "Diagn Mol Pathol[Journal] OR ",
    "Diagn Pathol[Journal] OR ",
    "Endocr Pathol[Journal] OR ",
    "Exp Mol Pathol[Journal] OR ",
    "Expert Rev Mol Diagn[Journal] OR ",
    "Fetal Pediatr Pathol[Journal] OR ",
    "Gastroenterology[Journal] OR ",
    "Gut[Journal] OR ",
    "Histol Histopathol[Journal] OR ",
    "Histopathology[Journal] OR ",
    "Hum Pathol[Journal] OR ",
    "Indian J Pathol Microbiol[Journal] OR ",
    "Int J Clin Exp Pathol[Journal] OR ",
    "Int J Exp Pathol[Journal] OR ",
    "Int J Immunopathol Pharmacol[Journal] OR ",
    "Int J Surg Pathol[Journal] OR ",
    "J Clin Pathol[Journal] OR ",
    "J Mol Diagn[Journal] OR ",
    "J Pathol[Journal] OR ",
    "Korean J Pathol[Journal] OR ",
    "Lab Invest[Journal] OR ",
    "Lancet[Journal] OR ",
    "Malays J Pathol[Journal] OR ",
    "Med Mol Morphol[Journal] OR ",
    "Mod Pathol[Journal] OR ",
    "N Engl J Med[Journal] OR ",
    "Nature[Journal] OR ",
    "Pancreas[Journal] OR ",
    "Pancreatology[Journal] OR ",
    "Pathobiology[Journal] OR ",
    "Pathol Biol [Journal] OR ",
    "Pathol Int[Journal] OR ",
    "Pathol Oncol Res[Journal] OR ",
    "Pathol Res Pract[Journal] OR ",
    "Pathologe[Journal] OR ",
    "Pathology[Journal] OR ",
    "Pediatr Dev Pathol[Journal] OR ",
    "Pol J Pathol[Journal] OR ",
    "Proc Natl Acad Sci U S A[Journal] OR ",
    "Science[Journal] OR ",
    "Semin Diagn Pathol[Journal] OR ",
    "Semin Immunopathol[Journal] OR ",
    "Surg Pathol Clin[Journal] OR ",
    "Turk Patoloji Derg[Journal] OR ",
    "Ultrastruct Pathol[Journal] OR ",
    "Virchows Arch[Journal]"
)
